[__config__]
oldver = "oldver.json"
newver = "newver.json"
nix-expr-folder = "."

[bench] # only used for some static outputs
source = "github"
github = "frappe/bench"

[frappe]
source = "github"
branch = "version-15-hotfix"
# use_max_tag = true
github = "frappe/frappe"

[frappe.passthru]
since = "version-14"
upstream = """
URL: https://github.com/frappe/frappe
Pull: +refs/heads/develop:refs/remotes/upstream/develop
Pull: +refs/heads/version-15:refs/remotes/upstream/version-15
Pull: +refs/heads/version-15-hotfix:refs/remotes/upstream/version-15-hotfix
Pull: +refs/tags/v15.*:refs/remotes/upstream/tags/v15.*
"""

[erpnext]
source = "github"
use_max_tag = true
github = "frappe/erpnext"

[erpnext.passthru]
since = "version-14"
upstream = """
URL: https://github.com/frappe/erpnext
Pull: +refs/heads/develop:refs/remotes/upstream/develop
Pull: +refs/heads/version-15:refs/remotes/upstream/version-15
Pull: +refs/heads/version-15-hotfix:refs/remotes/upstream/version-15-hotfix
Pull: +refs/tags/v15.*:refs/remotes/upstream/tags/v15.*
"""

[insights]
source = "github"
github = "frappe/insights"
use_max_tag = true
submodules = true

[gameplan]
source = "github"
branch = "patched"            # unmaintained? / no release yet
github = "blaggacao/gameplan"
use_commit = true
submodules = true

[crm]
source = "github"
github = "frappe/crm"
use_max_tag = true
submodules = true

[builder]
source = "github"
use_max_tag = true
github = "frappe/builder"
submodules = true

[print-designer]
source = "github"
use_max_tag = true
github = "frappe/print_designer"

[ecommerce-integrations]
source = "github"
github = "frappe/ecommerce_integrations"

[payments]
source = "github"
branch = "version-15"      # no proper releases
github = "frappe/payments"

[webshop]
source = "github"
branch = "version-15"     # no proper releases
github = "frappe/webshop"

[wiki]
source = "github"
branch = "master"      # Latest release (Wiki v2.0.1) is for frappe 14
github = "frappe/wiki"

[hrms]
source = "github"
use_max_tag = true
github = "frappe/hrms"
submodules = true

[raven]
source = "github"
use_max_tag = true
github = "The-Commit-Company/Raven"

[raven.passthru]
since = "v1.0.0"
upstream = """
URL: https://github.com/The-Commit-Company/Raven
Pull: +refs/heads/develop:refs/remotes/upstream/develop
Pull: +refs/heads/main:refs/remotes/upstream/main
"""

[drive]
source = "github"
use_max_tag = true
github = "frappe/drive"
