# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bench = {
    pname = "bench";
    version = "v5.22.3";
    src = fetchFromGitHub {
      owner = "frappe";
      repo = "bench";
      rev = "v5.22.3";
      fetchSubmodules = false;
      sha256 = "sha256-l42ZbovVUcm8WuRqESw1VdIWW8Ah+wHcYBQX/ML8REk=";
    };
  };
  ecommerce-integrations = {
    pname = "ecommerce-integrations";
    version = "v1.20.0";
    src = fetchFromGitHub {
      owner = "frappe";
      repo = "ecommerce_integrations";
      rev = "v1.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-ydJn38hOQ2kfFIp8ZmIGT7Jn/D2H5Op5OkI6NGBgOdk=";
    };
  };
  erpnext = {
    pname = "erpnext";
    version = "08caa7cfa15912f8b45d97088fed30c32e55db29";
    src = fetchFromGitHub {
      owner = "frappe";
      repo = "erpnext";
      rev = "08caa7cfa15912f8b45d97088fed30c32e55db29";
      fetchSubmodules = false;
      sha256 = "sha256-eofJ+Cy87BrZ1LD9NiqImFNBDQoLonLfb6BQ19EKYrk=";
    };
    date = "2024-02-26";
  };
  frappe = {
    pname = "frappe";
    version = "0934dfea93c22e111bd0c2b836273bc5b78adc9e";
    src = fetchFromGitHub {
      owner = "frappe";
      repo = "frappe";
      rev = "0934dfea93c22e111bd0c2b836273bc5b78adc9e";
      fetchSubmodules = false;
      sha256 = "sha256-ly6dopRikmqrDG4yGlBpqDvgchWOqoynDM+jmgh9SOg=";
    };
    date = "2024-02-26";
  };
  gameplan = {
    pname = "gameplan";
    version = "9f9332cf29496afe5e912e4f1734fbf1142cb18c";
    src = fetchFromGitHub {
      owner = "frappe";
      repo = "gameplan";
      rev = "9f9332cf29496afe5e912e4f1734fbf1142cb18c";
      fetchSubmodules = false;
      sha256 = "sha256-LhSoUr+sqtwGSnfu4aux8/NE09EzX+uNibiBgwXKJAA=";
    };
    date = "2024-02-06";
  };
  insights = {
    pname = "insights";
    version = "v2.1.2";
    src = fetchFromGitHub {
      owner = "frappe";
      repo = "insights";
      rev = "v2.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-Qope4iYQ+SoWahU7k8Fq+E4+iwdg5lZaAQHas/IDhoU=";
    };
  };
  payments = {
    pname = "payments";
    version = "54cc513fa9420a7fda48251099b1b158f3f9be6b";
    src = fetchFromGitHub {
      owner = "frappe";
      repo = "payments";
      rev = "54cc513fa9420a7fda48251099b1b158f3f9be6b";
      fetchSubmodules = false;
      sha256 = "sha256-y+yXbieiDMkYTyL6Fc95EQCnuRtqAD0WMBTU4xF3zxo=";
    };
    date = "2024-01-23";
  };
}
