#! /usr/bin/env bash

# optional, if you have a branded package
export OWNER=blaggacao
export REPO=frappix
export PACKAGE=frx

bash <(curl -L https://raw.githubusercontent.com/paisano-nix/onboarding/main/install)
